### ISSUE TITLE
undefined is not an object (evaluating 'NativeModules["SQLite"][method]')

### ISSUE THREAD

**Issue by tyw2015** [SystangoTechnologies/Crashalert#1]
rn-crash-repoter seems have some problem while I'm using it, the error output is like this:
undefined is not an object (evaluating 'NativeModules["SQLite"][method]')
exec
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native-sqlite-storage\lib\sqlite.core.js:84:26
open
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native-sqlite-storage\lib\sqlite.core.js:275:16
SQLitePlugin
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native-sqlite-storage\lib\sqlite.core.js:106:12
<unknown>
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native-sqlite-storage\lib\sqlite.core.js:774:26
<unknown>
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native-sqlite-storage\lib\sqlite.core.js:73:22
openDatabase
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\rn-crash-reporter\lib\SQLiteManager.js:60:40
SQLiteManager
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\rn-crash-reporter\lib\SQLiteManager.js:51:9
initializeDBIncetance
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\rn-crash-reporter\lib\CrashReporter.js:89:26
CrashReporter
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\rn-crash-reporter\lib\CrashReporter.js:50:6
componentWillMount
    C:\Users\tyw\Desktop\rn\RNTest\app\containers\app.js:62:4
proxiedMethod
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-proxy\modules\createPrototypeProxy.js:44:35
<unknown>
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1652:19
measureLifeCyclePerf
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1610:15
mountComponent
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1651:57
mountComponent
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1327:53
performInitialMount
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1703:54
mountComponent
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1655:184
mountComponent
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1327:53
performInitialMount
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1703:54
mountComponent
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1655:184
mountComponent
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1327:53
performInitialMount
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1703:54
mountComponent
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1655:184
mountComponent
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1327:53
mountChildren
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:2871:62
initializeChildren
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:2940:45
mountComponent
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:2969:84
mountComponent
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1327:53
performInitialMount
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1703:54
mountComponent
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1655:184
mountComponent
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1327:53
performInitialMount
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1703:54
mountComponent
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1655:184
mountComponent
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1327:53
mountChildren
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:2871:62
initializeChildren
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:2940:45
mountComponent
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:2969:84
mountComponent
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1327:53
performInitialMount
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1703:54
mountComponent
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1655:184
mountComponent
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1327:53
mountChildren
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:2871:62
initializeChildren
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:2940:45
mountComponent
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:2969:84
mountComponent
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1327:53
performInitialMount
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1703:54
mountComponent
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1655:184
mountComponent
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1327:53
performInitialMount
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1703:54
mountComponent
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1655:184
mountComponent
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1327:53
performInitialMount
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1703:54
mountComponent
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1655:184
mountComponent
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1327:53
mountComponentIntoNode
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1998:50
perform
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1382:99
batchedMountComponentIntoNode
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:2004:24
perform
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1382:99
batchedUpdates
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:2077:139
batchedUpdates$1
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1456:61
renderComponent
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:2032:45
render
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:3258:46
renderApplication
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native\Libraries\ReactNative\renderApplication.js:34:4
run
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native\Libraries\ReactNative\AppRegistry.js:117:10
runApplication
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native\Libraries\ReactNative\AppRegistry.js:191:26
__callFunction
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:266:47
<unknown>
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:103:26
__guard
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:231:6
callFunctionReturnFlushedQueue
    C:\Users\tyw\Desktop\rn\RNTest\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:102:17

**Comment by tyw2015** [comment]
and there is my JS demo:

...
import { CrashReporter, Configuration } from 'rn-crash-reporter';
...

class App extends Component {
...
  componentWillMount() {
    Configuration.setHostURL('http://192.168.11.69:8000');
    Configuration.setIsReportCrash(true)
    new CrashReporter()
  }
...
}

**Comment by amourya-systango** [comment]
Hey @tyw2015, could you please take a fresh pull and follow the steps written in README.md file again and test it again?

**Comment by amourya-systango** [comment]
For now I'm closing this issue as we have updated this library. If will experience any issue again then please create a new issue. Thanks!
